import Footer from "@/components/common/footer";
import Navbar from "@/components/common/navbar";
import type { Metadata } from "next";
import "swiper/css";
import "swiper/css/pagination";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`antialiased`} suppressHydrationWarning={true}>
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
